# html lang
language:

# Head info
# hitokoto: "lwl12", "i-meto"
head:
    favicon: "/img/favicon.ico"
    high_res_favicon: "/img/favicon.ico"
    apple_touch_icon: "/img/favicon.ico"
    keywords:
    hitokoto: ""

# You can use whatever you like
dynamic_title:

appbar:
  fixed:
    enable: true
    scroll_hide:

userview:
  avatar: "/img/avatar.png"
  bgimg: "/img/bg.png"
  email: "example@example.com"

# icon value from mdui.org
# text_color = theme, red, red-900
drawer:
  accordion: "false"
  subtitle: "????"
  holiday:
    enable:
    text:
    text_color: "red"
    bg_color:
  counter:
    enable:
    date:
    progress_bar:
  menu:
    divider:
    homepage:
      icon: "&#xe88a;"
      title:
      circle: true
      color:
      fix:
      text_color:
      bg_color:
    archives:
      enable: true
      icon: "&#xe156;"
      title: ""
      circle: true
      color:
      arrow:
      fix: true
      text_color:
      bg_color:
    categories:
      enable: true
      icon: "&#xe86d;"
      title:
      circle: true
      color:
      arrow:
      fix: true
      text_color:
      bg_color:
    archive:
      enable: true
      icon: "&#xe54b;"
      title:
      circle: true
      color:
      arrow:
      fix:
      text_color:
      bg_color:

pages:
  list:

  collapse:


background:
  color:
  img:

typinyin:
  title:

theme:
  layout:
  primary_color: indigo
  accent_color: indigo
  chang_theme: true

pace:
  style: center-atom
  color: "#3F51B5"

smoothscroll: true

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: local
    swiftype_key:

fab:
  trigger: "hover"
  main:
    first_icon: "&#xe145;"
    second_icon: "&#xe14c;"
  top:
    color: "pink"
    icon: "&#xe316;"
  prev:
    color: "red"
    icon: "&#xe314;"
  next:
    color: "orange"
    icon: "&#xe315;"

index_head_left:
  userview: "bottom"
  title: "img-bottom"
  gradient:
  slogan:
  img: "/img/bg.png"

index_head_right:
  userview:
  img: "/img/logo.png"

share_menu:
  article_rss:
  weibo:
  twitter:
  facebook:
  googleplus: true
  linkedin:
  qq:
  telegram: true

# userview: "top", "bottom", "center"
# title: "img-top", "img-bottom", "card-center", "card-top"
post:
  userview: "bottom"
  title: "img-bottom"
  gradient: ""
  entry_excerpt: 80
  img_color: "#536DFE"

qrcode: true

copyright:
  blog_start_year:

sns:


# Busuanzi 不蒜子 Views
busuanzi:
    enable:
    all_site_uv:
    post_pv:
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

comment:
    use:
    shortname:
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
