# CDN for mathjax
location:

# style
style:
  scheme:
  bg_img: /img/bg.png
  avatar: /img/avatar.png
  slogan: "I'm your slogan!"
  hoverable: true

# HTML head
head:
  favicon: /img/favicon.png
  high_res_favicon: /img/favicon.png
  apple_touch_icon: /img/favicon.png
  keywords: blog, hexo, mdui

# color
color:
  primary_color: "indigo"
  accent_color: "blue"
  layout:
  random:
  bg_color: "#eeeeee"

# appbar
appbar:
  title: "Title"

index:
  welcome: "Welcome to my blog~"

# post settings
post:
  entry_excerpt: 80
  # topPost: true
  donate:
    wechat: /img/avatar.png
    paypay: 'https://paypal.com'
  qr_code: true

share_menu: #false
  rss: false
  weibo: false
  twitter: true
  facebook: true
  googleplus: true
  linkedin: true
  qq: false
  telegram: false

comment:
    use:
    shortname:

# pagination
# github@zllovesuki
pagination: 2

# footer
footer:
  since:
  ICP:

# Plugins
busuanzi: #false
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

service_woker:

pages:
  Test1:
    link: "/myfriends"
    icon: "&#xe0ba;"
  Test99:
    link: "/myfriends"
    icon: "&#xe0ba;"
  Test8:
    link: "/myfriends"
    icon: "&#xe0ba;"
  Test877:
    link: "/myfriends"
    icon: "&#xe0ba;"
  Test8234:
    link: "/myfriends"
    icon: "&#xe0ba;"
  Test2:
    link: "/apply-for-link"
    icon: "&#xe7f0;"
  Test3:
    link: "/timeline"
    icon: "home"
  Test4:
    cascade: true
    icon: 'home'
    pages:
      TEST1:
        link: "/myfriends"
        icon: "&#xe5ca;"
      TEST2:
        link: "/timeline"
        icon: "home"
      Test3:
        link: "/timeline"
        icon: "home"

sns:
  Twitter: https://twitter.com
  Facebook: https://facebook.com

# Translations
translations:
  # archive: 'Archive'
  archives: 'Archives'
  category: 'Category'
  categories: 'Categories'
  index: 'Index'
  pages: 'Pages'
  tag: 'Tag'
  tags: 'Tags'
  years: 'Years'
  busuanzi_views: 'Views: '
  posts:
    header: 'Something that I have posted'
    public: 'Public'
  userview:
    contact_me: 'Contact me'
    how_to_contact_me: 'How to contact me'
    close: 'Close'
  share_menu:
    rss: 'Article RSS'
    facebook: 'Share to Facebook'
    googleplus: 'Share to Google+'
    linkedin: 'Share to Linkedin'
    qq: 'Share to QQ'
    telegram: 'Share to Telegram'
    twitter: 'Share to Twitter'
    weibo: 'Share to Weibo'
  snackbar: 'Oops! Nothing happened.'
  qr_code: "Article QR Code"
  donate:
    button: 'Buy me a beer?'
    close: 'cancel'
  friends_title: 'HI~~'
  outdated_browser:
    title: 'Your browser is out-of-date!'
    line_one: 'Update your browser to view this website correctly. '
    link: 'Update my browser now '
    close: 'Close'
  gallery_button_text: 'Enter gallery'
  disqus_no_script: 'Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>'
  post_pagination:
    newer: 'Newer Post'
    older: 'Older Post'
    no_newer: 'No More Newer Post'
    no_older: 'No More Older Post'

# Vendors
vendors:
  style_min_css:
  js_min_js:
  outdatedbrowser_min_js:
