# CDN server
location:

# HTML head
head:
  favicon: https://gravatar.com/userimage/113938008/e65085ec5e08a13de79873206f0c76fa.png?size=200
  high_res_favicon: https://gravatar.com/userimage/113938008/e65085ec5e08a13de79873206f0c76fa.png?size=200
  apple_touch_icon: https://gravatar.com/userimage/113938008/0ffede3b011b3a1725a0bae6b2db2c72.png?size=200
  keywords:

# color
color:
  primary_color: "indigo"
  accent_color: "blue"
  layout:

# appbar
appbar:
  title:

# post settings
post:
  # avatar: https://gravatar.com/userimage/113938008/e65085ec5e08a13de79873206f0c76fa.png?size=200
  entry_excerpt: 50

share_menu: #false
  weibo: true
  twitter: true
  facebook: true
  googleplus: true
  linkedin: true
  qq: true
  telegram: true

qr_code: true

comment:
    use:
    shortname:
    provider:

# pagination
# github@zllovesuki
index:
  show: 2

# footer
footer:
  start_year: 2016
  ICP:

# Plugins
busuanzi: #false
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

pages:
  友链:
    link: "/friends"
    icon: "&#xe0ba;"
  申请友链:
    link: "/apply-for-link"
    icon: "&#xe7fe;"

sns: false


# Translations
translations:
  # archive: '归档'
  archives: '归档'
  category: '分类'
  categories: '分类'
  index: '首页'
  pages: '页面'
  tag: '标签'
  tags: '标签'
  years: '年份'
  busuanzi_views: '浏览量: '
  footer:
    contact_me: '联系我'
    how_to_contact_me: '如何联系我'
    close: '本王知道了'
  share_menu:
    facebook: '分享到Facebook'
    googleplus: '分享到Google+'
    linkedin: '分享到Linkedin'
    qq: '分享到QQ'
    telegram: '分享到Telegram'
    twitter: '分享到Twitter'
    weibo: '分享到Weibo'
  snackbar: '这里...不可以...'
