# html lang
language: en

# HTML head
head:
  favicon: /img/favicon.png
  high_res_favicon: /img/favicon.png
  apple_touch_icon: /img/favicon.png
  keywords:

# color
color:
  primary_color: "indigo"
  accent_color: "blue"
  layout: ""

# appbar
appbar:
  title: "TITLE"

# post settings
post:
  avatar: /img/avatar.png
  entry_excerpt: 50

share_menu:
  weibo: true
  twitter: true
  facebook: true
  googleplus: true
  linkedin: true
  qq: true
  telegram: true

qr_code:

comment:
    use:
    shortname:
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
# pagination
# github@zllovesuki
index:
  show: 2

# footer
copyright:
  start_year: 2016

pages:
  Test1:
    link: "test1"
    icon: "&#xe84d;"
  Test2:
    link: "test1"
    icon: "&#xeb3b;"
  Test3:
    link: "test1"
    icon: "&#xe851;"

sns:
  Twitter: "https://twitter.com"
  Facebook: "https://facebook.com"

# Translations
translations:
  archive: '归档'
  archives: '归档'
  categories: '分类'
  index: '首页'
  pages: '页面'
  tag: '标签'
  tags: '标签'
  years: '年份'
  footer:
    contact_me: '联系我'
    how_to_contact_me: '如何联系我'
    close: '关闭'
  share_menu:
    facebook: '分享到脸书'
    googleplus: '分享到Google+'
    linkedin: '分享到领英'
    qq: '分享到QQ'
    telegram: '分享到Telegram'
    twitter: '分享到推特'
    weibo: '分享到微博'
