# html lang
language: en

# HTML head
head:
  favicon: /img/favicon.png
  high_res_favicon: /img/favicon.png
  apple_touch_icon: /img/favicon.png
  keywords:

# color
color:
  primary_color: "indigo"
  accent_color: "blue"
  layout: ""

# appbar
appbar:
  title: "TITLE"

# post settings
post:
  entry_excerpt: 50

# pagination
# github@zllovesuki
index:
  show: 2

# footer
copyright:
  start_year: 2016

pages:
  Test1:
    link: "test1"
    icon: "&#xe84d;"
  Test2:
    link: "test1"
    icon: "&#xeb3b;"
  Test3:
    link: "test1"
    icon: "&#xe851;"

sns:
  Twitter: "https://twitter.com"
  Facebook: "https://facebook.com"
