# HTML head
head:
  favicon: /img/favicon.png
  high_res_favicon: /img/favicon.png
  apple_touch_icon: /img/favicon.png
  keywords: blog, hexo, mdui

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

pages:
  Test1:
    link: "/myfriends"
    md: "&#xe0ba;"
  Test2:
    link: "/apply-for-link"
    fa: "fa-child"
  Test3:
    link: "/timeline"
    md: "home"
  Test4:
    cascade: true
    md: 'home'
    pages:
      TEST1:
        link: "/myfriends"
        md: "&#xe5ca;"
      TEST2:
        link: "/timeline"
        md: "home"

# footer
footer:
  since:
  ICP:
  image:

# scss
node_sass:
  debug: false
  outputStyle: nested
  precision: 5
  sourceComments: false
