# Theme config
style:
  primary_color: "yellow"
  accent_color: "blue"
  random:
  bg_color: "#eeeeee"

info:
  bg_image: /images/bg.png
  avatar: /images/avatar.png
  slogan: "I'm your slogan!"

# HTML head
head:
  favicon: /images/favicon.png
  high_res_favicon: /images/favicon.png
  apple_touch_icon: /images/favicon.png
  keywords: blog, hexo, mdui

pagination: 1

# main menu navigation
menu:
  Home: /

pages:
  Test1:
    link: "/myfriends"
    md: "&#xe0ba;"
  Test2:
    link: "/apply-for-link"
    fa: "fa-child"
  Test3:
    link: "/timeline"
    md: "home"
  Test4:
    cascade: true
    md: 'home'
    pages:
      TEST1:
        link: "/myfriends"
        md: "&#xe5ca;"
      TEST2:
        link: "/timeline"
        md: "home"

# footer
footer:
  since:
  ICP:
  image:

# scss
node_sass:
  debug: false
  outputStyle: nested
  precision: 5
  sourceComments: false
